name: semantique
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - datacube
  - geocube
  - geopandas
  - numpy
  - pandas
  - pyproj
  - pytz
  - pystac
  - rasterio
  - rioxarray
  - scipy
  - xarray
  - pip
  - pip:
    - hvplot
    - planetary-computer
    - pystack-client
    - stackstac
    - .