name: Sphinx build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup-conda-environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: semantique
        environment-file: environment.yml
    - name: install-build-requirements
      shell: bash -l {0}
      run: |
        sudo apt-get install -y pandoc
        pip install -r ./docs/requirements.txt
    - name: build
      shell: bash -l {0}
      run: |
        sphinx-build -b html ${SOURCE_DIR} ${BUILD_DIR}
      env:
        SOURCE_DIR: ./docs/source
        BUILD_DIR: ./docs/build
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build
        publish_branch: gh-pages