name: Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup-conda-environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: semantique
    - name: install-package-requirements
      shell: bash -l {0}
      run: |
        conda install geocube datacube
    - name: install-package
      shell: bash -l {0}
      run: |
        pip install -e .
    - name: test
      shell: bash -l {0}
      run: |
        python -m unittest discover